apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  labels:
    app: bankapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql-0.mysqlsvc 3306; do echo waiting for mysql; sleep 5; done;']
      containers:
      - name: bankapp
        image: joakim077/springboot-application
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key:  MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef:
              name: appconfig
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: SPRING_DATASOURCE_USERNAME
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

        
               
